### PR TITLE
Add me to About page, fix Jannes' name

### PR DESCRIPTION
**Pull request by FunctionDJ**

### CODE REVIEW

**Comment by lostdesign** [comment]
@waffln check the build logs - seems like you got an issue with the asset you added.

**Comment by lostdesign** [comment]
@waffln check preview, image is way too big - and aren't our images loaded from discord cdn or are they also static?

**Comment by waffln** [comment]
> @waffln check preview, image is way too big - and aren't our images loaded from discord cdn or are they also static?

@lostdesign Yeah i forgot to upload my photo :D

**Comment by FunctionDJ** [comment]
> @waffln check preview, image is way too big - and aren't our images loaded from discord cdn or are they also static?

LMAO will fix, they are static links
https://github.com/devcord/website/blob/464987df37bc4fdae07558ed55f50af4e28f391b/src/views/About.vue#L14

**Pull request merged**
